<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="3.12" timestamp="2022-03-15T18:12:38">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;docker_run&gt; returned non-zero exit code 125" type="BLOCKED"/>
		<system-out>18:12:35 INFO  ==============================================================
18:12:35 INFO  Id:    docker_plugin_update
18:12:35 INFO  Dir:   plugin_docker/
18:12:35 INFO  Title: Validate docker plugin install updates existing containers
18:12:35 DEBUG Execution order hint: 0.0
18:12:35 INFO  ==============================================================
18:12:35 DEBUG Process parameters for sudo&lt;docker_images&gt;
  command line : /usr/bin/sudo docker images
    arg #1     : docker
    arg #2     : images
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
18:12:35 DEBUG Waiting up to 600 secs for process sudo&lt;docker_images&gt; (pid 29484)
18:12:36 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
18:12:36 DEBUG Performing regex contains=False grep on file: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out
18:12:36 INFO  Grep on input file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
18:12:36 DEBUG Process parameters for sudo&lt;docker_run&gt;
  command line : /usr/bin/sudo docker run -d registry:2.6.2
    arg #1     : docker
    arg #2     : run
    arg #3     : -d
    arg #4     : registry:2.6.2
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_run.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_run.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
18:12:36 DEBUG Waiting up to 600 secs for process sudo&lt;docker_run&gt; (pid 29494)
18:12:38 WARN  Executed sudo&lt;docker_run&gt;, exit status 125
18:12:38 DEBUG Opening file using encoding=UTF-8: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_run.err
18:12:38 INFO  Contents of docker_run.err: 
18:12:38 INFO    Unable to find image 'registry:2.6.2' locally
18:12:38 INFO    docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
18:12:38 INFO    See 'docker run --help'.
18:12:38 INFO    -----
18:12:38 INFO  
18:12:38 WARN  sudo&lt;docker_run&gt; returned non-zero exit code 125 ... blocked 
18:12:38 WARN  Aborted test due to BLOCKED outcome
18:12:38 DEBUG --- test cleanup
18:12:38 INFO  
18:12:38 INFO  cleanup:
18:12:38 DEBUG Running registered cleanup function: &lt;bound method DockerPlugin.cleanup_containers of &lt;DockerPluginUpdateTest object at 0x7607e590&gt;&gt;
18:12:38 INFO  Removing containers scheduled to be cleaned up: ['9f7da16d968b', '']
18:12:38 DEBUG Process parameters for sudo&lt;containers_for_cleanup&gt;
  command line : /usr/bin/sudo docker rm -f 9f7da16d968b ''
    arg #1     : docker
    arg #2     : rm
    arg #3     : -f
    arg #4     : 9f7da16d968b
    arg #5     : 
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/containers_for_cleanup.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/containers_for_cleanup.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
18:12:38 DEBUG Waiting up to 600 secs for process sudo&lt;containers_for_cleanup&gt; (pid 29511)
18:12:38 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
18:12:38 DEBUG Running registered cleanup function: &lt;bound method DockerPlugin.cleanup_images of &lt;DockerPluginUpdateTest object at 0x7607e590&gt;&gt;
18:12:38 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1']
18:12:38 DEBUG Process parameters for sudo&lt;containers_for_cleanup&gt;
  command line : /usr/bin/sudo docker rmi -f registry registry registry:2.7.1
    arg #1     : docker
    arg #2     : rmi
    arg #3     : -f
    arg #4     : registry
    arg #5     : registry
    arg #6     : registry:2.7.1
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/containers_for_cleanup.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/containers_for_cleanup.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
18:12:38 DEBUG Waiting up to 600 secs for process sudo&lt;containers_for_cleanup&gt; (pid 29521)
18:12:38 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
18:12:38 DEBUG ProcessUser cleanup function done.
18:12:38 INFO  
18:12:38 INFO  Test duration: 3.12 secs
18:12:38 INFO  Test final outcome:  BLOCKED
18:12:38 INFO  Test outcome reason: sudo&lt;docker_run&gt; returned non-zero exit code 125
18:12:38 INFO  
</system-out>
	</testcase>
</testsuite>
