2022-04-19 13:45:58,400 INFO  ==============================================================
2022-04-19 13:45:58,401 INFO  Id:    tedge_mapper_c8y_child_device_measurement
2022-04-19 13:45:58,402 INFO  Dir:   tedge_mapper_c8y/
2022-04-19 13:45:58,403 INFO  Title: Validate that measurements sent to tedge/measurements/child topic gets mapped as the child device's measurement in Cumulocity
2022-04-19 13:45:58,404 INFO  ==============================================================
2022-04-19 13:45:58,441 INFO  EnvironmentC8y Setup
2022-04-19 13:45:59,003 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-04-19 13:45:59,117 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 5 seconds
2022-04-19 13:45:59,118 INFO  Delaying execution by 6 seconds
2022-04-19 13:46:20,050 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 14 secs
2022-04-19 13:46:20,670 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-04-19 13:46:21,184 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-04-19 13:46:21,647 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-04-19 13:46:22,663 INFO  Assert that (actual == expected) with actual=None, expected=None ... passed
2022-04-19 13:46:23,179 INFO  Executed tedge_pub, exit status 0
2022-04-19 13:46:23,646 INFO  Executed tedge_pub, exit status 0
2022-04-19 13:46:24,058 INFO  Executed tedge_pub, exit status 0
2022-04-19 13:46:24,470 INFO  Executed tedge_pub, exit status 0
2022-04-19 13:46:24,882 INFO  Executed tedge_pub, exit status 0
2022-04-19 13:46:27,574 WARN  TypeError occurred while running test - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1296, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_child_device_measurement/run.py", line 115, in validate
    self.child_device_json["id"], 3
TypeError: 'NoneType' object is not subscriptable
2022-04-19 13:46:27,596 WARN  TypeError: 'NoneType' object is not subscriptable ... blocked 
2022-04-19 13:46:27,597 INFO  
2022-04-19 13:46:27,598 INFO  cleanup:
2022-04-19 13:46:27,598 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py", line 1305, in cleanup
    fn()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_child_device_measurement/run.py", line 165, in test_cleanup
    self.child_device_json["id"]
TypeError: 'NoneType' object is not subscriptable
2022-04-19 13:46:31,709 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-04-19 13:46:32,325 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-04-19 13:46:32,337 WARN  Cleanup failed with 1 errors: Cleanup function failed: 'NoneType' object is not subscriptable (TypeError) ... blocked 
2022-04-19 13:46:32,341 INFO  
2022-04-19 13:46:32,342 INFO  Test duration: 33.95 secs
2022-04-19 13:46:32,343 INFO  Test final outcome:  BLOCKED
2022-04-19 13:46:32,344 INFO  Test outcome reason: TypeError: 'NoneType' object is not subscriptable (+1 other failures)
2022-04-19 13:46:32,345 INFO  
