<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="tedge_mapper_c8y_alarms" skipped="0" tests="1" time="31.16" timestamp="2022-04-14T07:02:35">
	<testcase classname="TedgeMapperC8yAlarm" name="tedge_mapper_c8y_alarms">
		<failure message="BLOCKED: IndexError: list index out of range" type="BLOCKED"/>
		<system-out>07:02:04 INFO  ==============================================================
07:02:04 INFO  Id:    tedge_mapper_c8y_alarms
07:02:04 INFO  Dir:   tedge_mapper_c8y/
07:02:04 INFO  Title: Validate that alarms sent to tedge/alarms topic \ gets mapped as alarms in Cumulocity
07:02:04 INFO  ==============================================================
07:02:04 INFO  EnvironmentC8y Setup
07:02:05 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
07:02:19 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
07:02:20 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
07:02:20 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
07:02:21 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
07:02:26 INFO  Executed tedge, exit status 0
07:02:26 INFO  Executed tedge, exit status 0
07:02:27 INFO  Executed tedge, exit status 0
07:02:27 INFO  Executed tedge, exit status 0
07:02:28 INFO  Executed tedge, exit status 0
07:02:29 WARN  IndexError occurred while running test - list index out of range
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1296, in __call__
    self.testObj.validate()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/tedge_mapper_c8y/tedge_mapper_c8y_alarms/run.py&quot;, line 100, in validate
    alarms[0],
IndexError: list index out of range
07:02:29 WARN  IndexError: list index out of range ... blocked 
07:02:29 INFO  
07:02:29 INFO  cleanup:
07:02:29 INFO  Executed tedge, exit status 0
07:02:30 INFO  Executed tedge, exit status 0
07:02:30 INFO  Executed tedge, exit status 0
07:02:35 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
07:02:35 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
07:02:35 INFO  
07:02:35 INFO  Test duration: 31.16 secs
07:02:35 INFO  Test final outcome:  BLOCKED
07:02:35 INFO  Test outcome reason: IndexError: list index out of range
07:02:35 INFO  
</system-out>
	</testcase>
</testsuite>
