<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="local_mqtt_pub_sub_with_sudo" skipped="0" tests="1" time="3.11" timestamp="2022-04-12T08:34:08">
	<testcase classname="PySysTest" name="local_mqtt_pub_sub_with_sudo">
		<failure message="FAILED: Grep on tedge_sub.out contains &quot;amessage&quot;" type="FAILED"/>
		<system-out>08:34:05 INFO  ==============================================================
08:34:05 INFO  Id:    local_mqtt_pub_sub_with_sudo
08:34:05 INFO  Dir:   local_mqtt/
08:34:05 INFO  Title: Validate local publishing and subscribing
08:34:05 INFO  ==============================================================
08:34:05 INFO  Started sudo&lt;tedge_sub&gt; with process id 2798
08:34:06 INFO  Executed sudo&lt;tedge_pub2&gt;, exit status 0
08:34:06 INFO  Executed sudo&lt;tedge_pub3&gt;, exit status 0
08:34:08 INFO  Executed sudo&lt;kill_out&gt;, exit status 0
08:34:08 WARN  Grep on tedge_sub.out contains &quot;amessage&quot; ... failed [run.py:61]
08:34:08 INFO  Grep on file tedge_sub.out ... passed
08:34:08 INFO  
08:34:08 INFO  Test duration: 3.11 secs
08:34:08 INFO  Test final outcome:  FAILED
08:34:08 INFO  Test outcome reason: Grep on tedge_sub.out contains &quot;amessage&quot;
08:34:08 INFO  
</system-out>
	</testcase>
</testsuite>
