2022-02-15 16:29:05,656 INFO  ==============================================================
2022-02-15 16:29:05,656 INFO  Id:    log_request_error_messages
2022-02-15 16:29:05,657 INFO  Dir:   log_request_end_to_end/
2022-02-15 16:29:05,657 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
2022-02-15 16:29:05,657 DEBUG Execution order hint: 0.0
2022-02-15 16:29:05,658 INFO  ==============================================================
2022-02-15 16:29:06,105 DEBUG EnvironmentC8y Setup
2022-02-15 16:29:06,106 INFO  EnvironmentC8y Setup
2022-02-15 16:29:06,107 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:06,111 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 13846)
2022-02-15 16:29:06,314 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-15 16:29:06,364 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 1 seconds
2022-02-15 16:29:06,365 INFO  Delaying execution by 10 seconds
2022-02-15 16:29:16,377 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:16,385 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 13850)
2022-02-15 16:29:27,457 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 11 secs
2022-02-15 16:29:27,459 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:27,463 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 14011)
2022-02-15 16:29:27,724 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-15 16:29:27,726 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:27,731 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 14014)
2022-02-15 16:29:27,945 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-15 16:29:27,947 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:27,952 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 14015)
2022-02-15 16:29:28,218 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-15 16:29:28,221 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:28,230 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 14023)
2022-02-15 16:29:28,486 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-15 16:29:28,490 DEBUG Process parameters for sudo<move_logs>
  command line : /usr/bin/sudo sh -c 'mv /tmp/sw_logs/* /var/log/tedge/agent/'
    arg #1     : sh
    arg #2     : -c
    arg #3     : mv /tmp/sw_logs/* /var/log/tedge/agent/
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/move_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/move_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:28,495 DEBUG Waiting up to 600 secs for process sudo<move_logs> (pid 14025)
2022-02-15 16:29:28,749 INFO  Executed sudo<move_logs>, exit status 0
2022-02-15 16:29:28,750 DEBUG --- test execute
2022-02-15 16:29:28,977 DEBUG --- test validate
2022-02-15 16:29:29,134 INFO  log response None
2022-02-15 16:29:30,315 INFO  log response None
2022-02-15 16:29:31,494 INFO  log response None
2022-02-15 16:29:32,675 INFO  log response None
2022-02-15 16:29:33,853 INFO  log response None
2022-02-15 16:29:35,029 INFO  log response None
2022-02-15 16:29:36,197 INFO  log response None
2022-02-15 16:29:37,378 INFO  log response None
2022-02-15 16:29:38,546 INFO  log response None
2022-02-15 16:29:39,732 INFO  log response None
2022-02-15 16:29:40,903 INFO  log response None
2022-02-15 16:29:42,081 INFO  log response None
2022-02-15 16:29:43,257 INFO  log response None
2022-02-15 16:29:44,436 INFO  log response None
2022-02-15 16:29:45,619 INFO  log response None
2022-02-15 16:29:46,793 INFO  log response None
2022-02-15 16:29:47,962 INFO  log response None
2022-02-15 16:29:49,135 INFO  log response None
2022-02-15 16:29:50,297 INFO  log response None
2022-02-15 16:29:51,436 INFO  log response None
2022-02-15 16:29:51,437 WARN  caught <class 'Exception'> while running test: retry
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1211, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py", line 43, in validate
    value=self.wait_until_logs_retrieved())
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py", line 52, in wait_until_logs_retrieved
    raise Exception("retry")
Exception: retry
2022-02-15 16:29:51,571 WARN  Exception: retry ... blocked 
2022-02-15 16:29:51,571 DEBUG --- test cleanup
2022-02-15 16:29:51,572 INFO  
2022-02-15 16:29:51,572 INFO  cleanup:
2022-02-15 16:29:51,572 DEBUG Running registered cleanup function: <bound method LogRequestVerifySearchTextError.cleanup_logs of <LogRequestVerifySearchTextError object at 0x753c5c30>>
2022-02-15 16:29:51,573 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo sh -c 'rm -rf /var/log/tedge/agent/example-*'
    arg #1     : sh
    arg #2     : -c
    arg #3     : rm -rf /var/log/tedge/agent/example-*
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:51,578 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 14030)
2022-02-15 16:29:51,781 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-15 16:29:51,782 DEBUG Process parameters for sudo<rm_tmp_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_tmp_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_tmp_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:51,787 DEBUG Waiting up to 600 secs for process sudo<rm_tmp_logs> (pid 14033)
2022-02-15 16:29:51,990 INFO  Executed sudo<rm_tmp_logs>, exit status 0
2022-02-15 16:29:51,991 DEBUG Process parameters for sudo<send_failed>
  command line : /usr/bin/sudo /usr/bin/tedge mqtt pub c8y/s/us 502,c8y_LogfileRequest
    arg #1     : /usr/bin/tedge
    arg #2     : mqtt
    arg #3     : pub
    arg #4     : c8y/s/us
    arg #5     : 502,c8y_LogfileRequest
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/send_failed.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/send_failed.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:51,996 DEBUG Waiting up to 600 secs for process sudo<send_failed> (pid 14035)
2022-02-15 16:29:52,199 INFO  Executed sudo<send_failed>, exit status 0
2022-02-15 16:29:52,200 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <LogRequestVerifySearchTextError object at 0x753c5c30>>
2022-02-15 16:29:52,200 DEBUG EnvironmentC8y Cleanup
2022-02-15 16:29:52,254 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:52,259 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 14041)
2022-02-15 16:29:55,173 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-15 16:29:55,175 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-15 16:29:55,179 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 14099)
2022-02-15 16:29:55,383 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-15 16:29:55,385 DEBUG ProcessUser cleanup function done.
2022-02-15 16:29:55,387 INFO  
2022-02-15 16:29:55,388 INFO  Test duration: 49.73 secs
2022-02-15 16:29:55,388 INFO  Test final outcome:  BLOCKED
2022-02-15 16:29:55,389 INFO  Test outcome reason: Exception: retry
2022-02-15 16:29:55,389 INFO  
