2022-02-22 11:27:31,201 INFO  ==============================================================
2022-02-22 11:27:31,202 INFO  Id:    log_request_error_messages
2022-02-22 11:27:31,202 INFO  Dir:   log_request_end_to_end/
2022-02-22 11:27:31,203 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
2022-02-22 11:27:31,203 DEBUG Execution order hint: 0.0
2022-02-22 11:27:31,203 INFO  ==============================================================
2022-02-22 11:27:31,652 DEBUG EnvironmentC8y Setup
2022-02-22 11:27:31,652 INFO  EnvironmentC8y Setup
2022-02-22 11:27:31,653 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:31,657 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 6191)
2022-02-22 11:27:31,861 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-22 11:27:31,910 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 1 seconds
2022-02-22 11:27:31,911 INFO  Delaying execution by 10 seconds
2022-02-22 11:27:41,923 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:41,931 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 6196)
2022-02-22 11:27:51,787 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-02-22 11:27:51,788 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:51,793 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 6318)
2022-02-22 11:27:52,049 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-22 11:27:52,051 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:52,056 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 6321)
2022-02-22 11:27:52,259 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-22 11:27:52,261 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:52,266 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 6322)
2022-02-22 11:27:52,470 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-22 11:27:52,471 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:52,482 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 6323)
2022-02-22 11:27:52,685 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-22 11:27:52,688 DEBUG Process parameters for sudo<move_logs>
  command line : /usr/bin/sudo sh -c 'mv /tmp/sw_logs/* /var/log/tedge/agent/'
    arg #1     : sh
    arg #2     : -c
    arg #3     : mv /tmp/sw_logs/* /var/log/tedge/agent/
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/move_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/move_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:27:52,693 DEBUG Waiting up to 600 secs for process sudo<move_logs> (pid 6325)
2022-02-22 11:27:52,896 INFO  Executed sudo<move_logs>, exit status 0
2022-02-22 11:27:52,897 DEBUG --- test execute
2022-02-22 11:27:53,073 DEBUG --- test validate
2022-02-22 11:27:53,198 INFO  log response None
2022-02-22 11:27:54,379 INFO  log response None
2022-02-22 11:27:55,551 INFO  log response None
2022-02-22 11:27:56,735 INFO  log response None
2022-02-22 11:27:57,913 INFO  log response None
2022-02-22 11:27:59,093 INFO  log response None
2022-02-22 11:28:00,268 INFO  log response None
2022-02-22 11:28:01,438 INFO  log response None
2022-02-22 11:28:02,613 INFO  log response None
2022-02-22 11:28:03,790 INFO  log response None
2022-02-22 11:28:04,922 INFO  log response None
2022-02-22 11:28:06,051 INFO  log response None
2022-02-22 11:28:07,175 INFO  log response None
2022-02-22 11:28:08,350 INFO  log response None
2022-02-22 11:28:09,517 INFO  log response None
2022-02-22 11:28:10,687 INFO  log response None
2022-02-22 11:28:11,858 INFO  log response None
2022-02-22 11:28:13,017 INFO  log response None
2022-02-22 11:28:14,204 INFO  log response None
2022-02-22 11:28:15,379 INFO  log response None
2022-02-22 11:28:15,380 WARN  caught <class 'Exception'> while running test: retry
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1211, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py", line 43, in validate
    value=self.wait_until_logs_retrieved())
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py", line 52, in wait_until_logs_retrieved
    raise Exception("retry")
Exception: retry
2022-02-22 11:28:15,515 WARN  Exception: retry ... blocked 
2022-02-22 11:28:15,516 DEBUG --- test cleanup
2022-02-22 11:28:15,516 INFO  
2022-02-22 11:28:15,516 INFO  cleanup:
2022-02-22 11:28:15,517 DEBUG Running registered cleanup function: <bound method LogRequestVerifySearchTextError.cleanup_logs of <LogRequestVerifySearchTextError object at 0x75364bd0>>
2022-02-22 11:28:15,517 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo sh -c 'rm -rf /var/log/tedge/agent/example-*'
    arg #1     : sh
    arg #2     : -c
    arg #3     : rm -rf /var/log/tedge/agent/example-*
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:28:15,522 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 6330)
2022-02-22 11:28:15,725 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-22 11:28:15,727 DEBUG Process parameters for sudo<rm_tmp_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_tmp_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/rm_tmp_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:28:15,731 DEBUG Waiting up to 600 secs for process sudo<rm_tmp_logs> (pid 6333)
2022-02-22 11:28:15,934 INFO  Executed sudo<rm_tmp_logs>, exit status 0
2022-02-22 11:28:15,936 DEBUG Process parameters for sudo<send_failed>
  command line : /usr/bin/sudo /usr/bin/tedge mqtt pub c8y/s/us 502,c8y_LogfileRequest
    arg #1     : /usr/bin/tedge
    arg #2     : mqtt
    arg #3     : pub
    arg #4     : c8y/s/us
    arg #5     : 502,c8y_LogfileRequest
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/send_failed.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/send_failed.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:28:15,940 DEBUG Waiting up to 600 secs for process sudo<send_failed> (pid 6335)
2022-02-22 11:28:16,193 INFO  Executed sudo<send_failed>, exit status 0
2022-02-22 11:28:16,194 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <LogRequestVerifySearchTextError object at 0x75364bd0>>
2022-02-22 11:28:16,195 DEBUG EnvironmentC8y Cleanup
2022-02-22 11:28:16,244 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:28:16,249 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 6341)
2022-02-22 11:28:18,414 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-22 11:28:18,415 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-22 11:28:18,420 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 6383)
2022-02-22 11:28:18,623 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-22 11:28:18,624 DEBUG ProcessUser cleanup function done.
2022-02-22 11:28:18,625 INFO  
2022-02-22 11:28:18,626 INFO  Test duration: 47.42 secs
2022-02-22 11:28:18,626 INFO  Test final outcome:  BLOCKED
2022-02-22 11:28:18,626 INFO  Test outcome reason: Exception: retry
2022-02-22 11:28:18,627 INFO  
