<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="SoftwareManagement.sm_mapper_fail_and_reconnect" skipped="0" tests="1" time="0.03" timestamp="2022-03-02T13:27:49">
	<testcase classname="MapperC8yReceiveLastMessageOnRestart" name="SoftwareManagement.sm_mapper_fail_and_reconnect">
		<failure message="BLOCKED: Failed to set up test: name 'BaseTest' is not defined" type="BLOCKED"/>
		<system-out>13:27:49 INFO  ==============================================================
13:27:49 INFO  Id:    SoftwareManagement.sm_mapper_fail_and_reconnect
13:27:49 INFO  Dir:   software_management_end_to_end/
13:27:49 INFO  Title: Validate the tedge-mapper-sm-c8y for receiving the last message on restart
13:27:49 DEBUG Execution order hint: 0.0
13:27:49 INFO  ==============================================================
13:27:49 WARN  Failed to set up test: name 'BaseTest' is not defined ... blocked 
13:27:49 WARN  caught &lt;class 'NameError'&gt; while setting up test SoftwareManagement.sm_mapper_fail_and_reconnect: name 'BaseTest' is not defined
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1143, in __call__
    exec(runpycode, runpy_namespace)
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/software_management_end_to_end/sm_mapper_fail_and_reconnect/run.py&quot;, line 27, in &lt;module&gt;
    class MapperC8yReceiveLastMessageOnRestart(BaseTest):
NameError: name 'BaseTest' is not defined
13:27:49 DEBUG --- test cleanup
13:27:49 DEBUG ProcessUser cleanup function done.
13:27:49 INFO  
13:27:49 INFO  Test duration: 0.03 secs
13:27:49 INFO  Test final outcome:  BLOCKED
13:27:49 INFO  Test outcome reason: Failed to set up test: name 'BaseTest' is not defined
13:27:49 INFO  
</system-out>
	</testcase>
</testsuite>
