2022-03-02 08:41:07,447 INFO  ==============================================================
2022-03-02 08:41:07,448 INFO  Id:    log_request_num_lines
2022-03-02 08:41:07,449 INFO  Dir:   log_request_end_to_end/
2022-03-02 08:41:07,449 INFO  Title: Validate end to end behaviour for the log request operation check for number of lines
2022-03-02 08:41:07,450 DEBUG Execution order hint: 0.0
2022-03-02 08:41:07,450 INFO  ==============================================================
2022-03-02 08:41:07,456 DEBUG EnvironmentC8y Setup
2022-03-02 08:41:07,457 INFO  EnvironmentC8y Setup
2022-03-02 08:41:07,458 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:07,462 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 11848)
2022-03-02 08:41:07,767 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-03-02 08:41:07,845 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
2022-03-02 08:41:07,846 INFO  Delaying execution by 8 seconds
2022-03-02 08:41:15,858 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:15,866 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 11853)
2022-03-02 08:41:25,895 INFO  Executed sudo<tedge_connect_c8y>, exit status 0
2022-03-02 08:41:25,899 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:25,905 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 11960)
2022-03-02 08:41:26,261 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-03-02 08:41:26,262 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:26,267 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 11969)
2022-03-02 08:41:26,522 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-03-02 08:41:26,523 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:26,528 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 11970)
2022-03-02 08:41:26,783 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-03-02 08:41:26,784 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:26,789 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 11971)
2022-03-02 08:41:27,094 INFO  Executed sudo<rm_logs>, exit status 0
2022-03-02 08:41:27,110 DEBUG Process parameters for sudo<move_logs>
  command line : /usr/bin/sudo sh -c 'mv /tmp/sw_logs/* /var/log/tedge/agent/'
    arg #1     : sh
    arg #2     : -c
    arg #3     : mv /tmp/sw_logs/* /var/log/tedge/agent/
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/move_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/move_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:27,115 DEBUG Waiting up to 600 secs for process sudo<move_logs> (pid 11973)
2022-03-02 08:41:27,420 INFO  Executed sudo<move_logs>, exit status 0
2022-03-02 08:41:27,421 DEBUG --- test execute
2022-03-02 08:41:27,614 DEBUG --- test validate
2022-03-02 08:41:27,785 INFO  log response None
2022-03-02 08:41:28,950 INFO  log response None
2022-03-02 08:41:30,115 INFO  log response None
2022-03-02 08:41:31,274 INFO  log response None
2022-03-02 08:41:32,446 INFO  log response None
2022-03-02 08:41:33,612 INFO  log response None
2022-03-02 08:41:34,756 INFO  log response None
2022-03-02 08:41:35,906 INFO  log response None
2022-03-02 08:41:37,063 INFO  log response None
2022-03-02 08:41:38,222 INFO  log response None
2022-03-02 08:41:39,376 INFO  log response None
2022-03-02 08:41:40,534 INFO  log response None
2022-03-02 08:41:41,691 INFO  log response None
2022-03-02 08:41:42,835 INFO  log response None
2022-03-02 08:41:43,992 INFO  log response None
2022-03-02 08:41:45,151 INFO  log response None
2022-03-02 08:41:46,307 INFO  log response None
2022-03-02 08:41:47,469 INFO  log response None
2022-03-02 08:41:48,625 INFO  log response None
2022-03-02 08:41:49,777 INFO  log response None
2022-03-02 08:41:49,778 WARN  caught <class 'Exception'> while running test: retry
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1211, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py", line 44, in validate
    value=self.wait_until_logs_retrieved())
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py", line 52, in wait_until_logs_retrieved
    raise Exception("retry")
Exception: retry
2022-03-02 08:41:49,791 WARN  Exception: retry ... blocked 
2022-03-02 08:41:49,792 DEBUG --- test cleanup
2022-03-02 08:41:49,793 INFO  
2022-03-02 08:41:49,793 INFO  cleanup:
2022-03-02 08:41:49,793 DEBUG Running registered cleanup function: <bound method LogRequestVerifyNumberOfLines.cleanup_logs of <LogRequestVerifyNumberOfLines object at 0x75c379d0>>
2022-03-02 08:41:49,796 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo sh -c 'rm -rf /var/log/tedge/agent/example-*'
    arg #1     : sh
    arg #2     : -c
    arg #3     : rm -rf /var/log/tedge/agent/example-*
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:49,801 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 11979)
2022-03-02 08:41:50,106 INFO  Executed sudo<rm_logs>, exit status 0
2022-03-02 08:41:50,109 DEBUG Process parameters for sudo<rm_tmp_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_tmp_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_tmp_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:50,116 DEBUG Waiting up to 600 secs for process sudo<rm_tmp_logs> (pid 11982)
2022-03-02 08:41:50,422 INFO  Executed sudo<rm_tmp_logs>, exit status 0
2022-03-02 08:41:50,425 DEBUG Process parameters for sudo<send_failed>
  command line : /usr/bin/sudo /usr/bin/tedge mqtt pub c8y/s/us 502,c8y_LogfileRequest
    arg #1     : /usr/bin/tedge
    arg #2     : mqtt
    arg #3     : pub
    arg #4     : c8y/s/us
    arg #5     : 502,c8y_LogfileRequest
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/send_failed.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/send_failed.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:50,433 DEBUG Waiting up to 600 secs for process sudo<send_failed> (pid 11984)
2022-03-02 08:41:50,739 INFO  Executed sudo<send_failed>, exit status 0
2022-03-02 08:41:50,740 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <LogRequestVerifyNumberOfLines object at 0x75c379d0>>
2022-03-02 08:41:50,741 DEBUG EnvironmentC8y Cleanup
2022-03-02 08:41:50,827 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:50,833 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 11989)
2022-03-02 08:41:53,166 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-03-02 08:41:53,168 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-03-02 08:41:53,175 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 12029)
2022-03-02 08:41:53,480 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-03-02 08:41:53,481 DEBUG ProcessUser cleanup function done.
2022-03-02 08:41:53,484 INFO  
2022-03-02 08:41:53,484 INFO  Test duration: 46.04 secs
2022-03-02 08:41:53,485 INFO  Test final outcome:  BLOCKED
2022-03-02 08:41:53,486 INFO  Test outcome reason: Exception: retry
2022-03-02 08:41:53,486 INFO  
