2022-02-16 09:22:15,409 INFO  ==============================================================
2022-02-16 09:22:15,410 INFO  Id:    log_request_num_lines
2022-02-16 09:22:15,410 INFO  Dir:   log_request_end_to_end/
2022-02-16 09:22:15,411 INFO  Title: Validate end to end behaviour for the log request operation check for number of lines
2022-02-16 09:22:15,411 DEBUG Execution order hint: 0.0
2022-02-16 09:22:15,412 INFO  ==============================================================
2022-02-16 09:22:15,417 DEBUG EnvironmentC8y Setup
2022-02-16 09:22:15,418 INFO  EnvironmentC8y Setup
2022-02-16 09:22:15,419 DEBUG Process parameters for systemctl<serv_mapper1>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper1.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper1.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:15,423 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper1> (pid 29708)
2022-02-16 09:22:15,728 INFO  Executed systemctl<serv_mapper1>, exit status 3
2022-02-16 09:22:15,799 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 3 seconds
2022-02-16 09:22:15,800 INFO  Delaying execution by 8 seconds
2022-02-16 09:22:23,813 DEBUG Process parameters for sudo<tedge_connect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:23,822 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y> (pid 29712)
2022-02-16 09:22:35,201 INFO  Executed sudo<tedge_connect_c8y>, exit status 0, duration 11 secs
2022-02-16 09:22:35,205 DEBUG Process parameters for sudo<tedge_connect_c8y_test>
  command line : /usr/bin/sudo /usr/bin/tedge connect c8y --test
    arg #1     : /usr/bin/tedge
    arg #2     : connect
    arg #3     : c8y
    arg #4     : --test
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y_test.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_connect_c8y_test.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:35,211 DEBUG Waiting up to 600 secs for process sudo<tedge_connect_c8y_test> (pid 29862)
2022-02-16 09:22:35,566 INFO  Executed sudo<tedge_connect_c8y_test>, exit status 0
2022-02-16 09:22:35,569 DEBUG Process parameters for systemctl<serv_mosq2>
  command line : /usr/bin/systemctl status mosquitto
    arg #1     : status
    arg #2     : mosquitto
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mosq2.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mosq2.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:35,574 DEBUG Waiting up to 600 secs for process systemctl<serv_mosq2> (pid 29870)
2022-02-16 09:22:35,837 INFO  Executed systemctl<serv_mosq2>, exit status 0
2022-02-16 09:22:35,839 DEBUG Process parameters for systemctl<serv_mapper3>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper3.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper3.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:35,845 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper3> (pid 29871)
2022-02-16 09:22:36,111 INFO  Executed systemctl<serv_mapper3>, exit status 0
2022-02-16 09:22:36,113 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:36,118 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 29872)
2022-02-16 09:22:36,422 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-16 09:22:36,438 DEBUG Process parameters for sudo<move_logs>
  command line : /usr/bin/sudo sh -c 'mv /tmp/sw_logs/* /var/log/tedge/agent/'
    arg #1     : sh
    arg #2     : -c
    arg #3     : mv /tmp/sw_logs/* /var/log/tedge/agent/
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/move_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/move_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:36,442 DEBUG Waiting up to 600 secs for process sudo<move_logs> (pid 29874)
2022-02-16 09:22:36,747 INFO  Executed sudo<move_logs>, exit status 0
2022-02-16 09:22:36,748 DEBUG --- test execute
2022-02-16 09:22:36,925 DEBUG --- test validate
2022-02-16 09:22:37,067 INFO  log response None
2022-02-16 09:22:38,233 INFO  log response None
2022-02-16 09:22:39,391 INFO  log response None
2022-02-16 09:22:40,555 INFO  log response None
2022-02-16 09:22:41,712 INFO  log response None
2022-02-16 09:22:42,869 INFO  log response None
2022-02-16 09:22:44,026 INFO  log response None
2022-02-16 09:22:45,192 INFO  log response None
2022-02-16 09:22:46,352 INFO  log response None
2022-02-16 09:22:47,517 INFO  log response None
2022-02-16 09:22:48,680 INFO  log response None
2022-02-16 09:22:49,845 INFO  log response None
2022-02-16 09:22:50,998 INFO  log response None
2022-02-16 09:22:52,160 INFO  log response None
2022-02-16 09:22:53,328 INFO  log response None
2022-02-16 09:22:54,494 INFO  log response None
2022-02-16 09:22:55,653 INFO  log response None
2022-02-16 09:22:56,818 INFO  log response None
2022-02-16 09:22:57,976 INFO  log response None
2022-02-16 09:22:59,126 INFO  log response None
2022-02-16 09:22:59,127 WARN  caught <class 'Exception'> while running test: retry
Traceback (most recent call last):
  File "/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py", line 1211, in __call__
    self.testObj.validate()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py", line 44, in validate
    value=self.wait_until_logs_retrieved())
  File "/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py", line 52, in wait_until_logs_retrieved
    raise Exception("retry")
Exception: retry
2022-02-16 09:22:59,138 WARN  Exception: retry ... blocked 
2022-02-16 09:22:59,139 DEBUG --- test cleanup
2022-02-16 09:22:59,139 INFO  
2022-02-16 09:22:59,139 INFO  cleanup:
2022-02-16 09:22:59,140 DEBUG Running registered cleanup function: <bound method LogRequestVerifyNumberOfLines.cleanup_logs of <LogRequestVerifyNumberOfLines object at 0x75d84510>>
2022-02-16 09:22:59,142 DEBUG Process parameters for sudo<rm_logs>
  command line : /usr/bin/sudo sh -c 'rm -rf /var/log/tedge/agent/example-*'
    arg #1     : sh
    arg #2     : -c
    arg #3     : rm -rf /var/log/tedge/agent/example-*
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:59,147 DEBUG Waiting up to 600 secs for process sudo<rm_logs> (pid 29884)
2022-02-16 09:22:59,452 INFO  Executed sudo<rm_logs>, exit status 0
2022-02-16 09:22:59,454 DEBUG Process parameters for sudo<rm_tmp_logs>
  command line : /usr/bin/sudo rm -rf /tmp/sw_logs
    arg #1     : rm
    arg #2     : -rf
    arg #3     : /tmp/sw_logs
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_tmp_logs.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/rm_tmp_logs.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:59,462 DEBUG Waiting up to 600 secs for process sudo<rm_tmp_logs> (pid 29887)
2022-02-16 09:22:59,767 INFO  Executed sudo<rm_tmp_logs>, exit status 0
2022-02-16 09:22:59,769 DEBUG Process parameters for sudo<send_failed>
  command line : /usr/bin/sudo /usr/bin/tedge mqtt pub c8y/s/us 502,c8y_LogfileRequest
    arg #1     : /usr/bin/tedge
    arg #2     : mqtt
    arg #3     : pub
    arg #4     : c8y/s/us
    arg #5     : 502,c8y_LogfileRequest
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/send_failed.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/send_failed.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:22:59,777 DEBUG Waiting up to 600 secs for process sudo<send_failed> (pid 29889)
2022-02-16 09:23:00,083 INFO  Executed sudo<send_failed>, exit status 0
2022-02-16 09:23:00,084 DEBUG Running registered cleanup function: <bound method EnvironmentC8y.myenvcleanup of <LogRequestVerifyNumberOfLines object at 0x75d84510>>
2022-02-16 09:23:00,085 DEBUG EnvironmentC8y Cleanup
2022-02-16 09:23:00,174 DEBUG Process parameters for sudo<tedge_disconnect_c8y>
  command line : /usr/bin/sudo /usr/bin/tedge disconnect c8y
    arg #1     : /usr/bin/tedge
    arg #2     : disconnect
    arg #3     : c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_disconnect_c8y.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/tedge_disconnect_c8y.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:23:00,179 DEBUG Waiting up to 600 secs for process sudo<tedge_disconnect_c8y> (pid 29895)
2022-02-16 09:23:03,449 INFO  Executed sudo<tedge_disconnect_c8y>, exit status 0
2022-02-16 09:23:03,451 DEBUG Process parameters for systemctl<serv_mapper5>
  command line : /usr/bin/systemctl status tedge-mapper-c8y
    arg #1     : status
    arg #2     : tedge-mapper-c8y
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper5.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/Output/linux/serv_mapper5.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-16 09:23:03,457 DEBUG Waiting up to 600 secs for process systemctl<serv_mapper5> (pid 29955)
2022-02-16 09:23:03,762 INFO  Executed systemctl<serv_mapper5>, exit status 3
2022-02-16 09:23:03,763 DEBUG ProcessUser cleanup function done.
2022-02-16 09:23:03,765 INFO  
2022-02-16 09:23:03,766 INFO  Test duration: 48.36 secs
2022-02-16 09:23:03,767 INFO  Test final outcome:  BLOCKED
2022-02-16 09:23:03,767 INFO  Test outcome reason: Exception: retry
2022-02-16 09:23:03,768 INFO  
