2022-02-25 16:15:06,548 INFO  ==============================================================
2022-02-25 16:15:06,549 INFO  Id:    apt_wrong_option
2022-02-25 16:15:06,549 INFO  Dir:   plugin_apt/
2022-02-25 16:15:06,550 INFO  Title: Validate apt plugin install
2022-02-25 16:15:06,550 DEBUG Execution order hint: 0.0
2022-02-25 16:15:06,550 INFO  ==============================================================
2022-02-25 16:15:06,554 DEBUG --- test execute
2022-02-25 16:15:06,555 DEBUG Process parameters for sudo<outp>
  command line : /usr/bin/sudo /etc/tedge/sm-plugins/apt nonsense
    arg #1     : /etc/tedge/sm-plugins/apt
    arg #2     : nonsense
  working dir  : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_wrong_option/Output/linux
  stdout       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_wrong_option/Output/linux/outp.out
  stderr       : /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_wrong_option/Output/linux/outp.err
  environment  : LD_LIBRARY_PATH=/usr/lib
  environment  : PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
                   #1  /bin
                   #2  /usr/bin
                   #3  /usr/sbin
                   #4  /usr/local/bin
2022-02-25 16:15:06,560 DEBUG Waiting up to 600 secs for process sudo<outp> (pid 3934)
2022-02-25 16:15:06,864 WARN  Executed sudo<outp>, exit status 2
2022-02-25 16:15:06,866 DEBUG Opening file using encoding=UTF-8: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apt/apt_wrong_option/Output/linux/outp.err
2022-02-25 16:15:06,870 INFO  Contents of outp.err: 
2022-02-25 16:15:06,871 INFO    error: Found argument 'nonsense' which wasn't expected, or isn't valid in this context
2022-02-25 16:15:06,872 INFO    USAGE:
2022-02-25 16:15:06,873 INFO        apt <SUBCOMMAND>
2022-02-25 16:15:06,874 INFO    For more information try --help
2022-02-25 16:15:06,874 INFO    -----
2022-02-25 16:15:06,875 INFO  
2022-02-25 16:15:06,901 WARN  sudo<outp> returned exit code 2 (expected ==1) ... blocked [environment_apt_plugin.py:70,run.py:17]
2022-02-25 16:15:06,901 WARN  Aborted test due to BLOCKED outcome
2022-02-25 16:15:06,905 DEBUG --- test cleanup
2022-02-25 16:15:06,905 DEBUG ProcessUser cleanup function done.
2022-02-25 16:15:06,907 INFO  
2022-02-25 16:15:06,908 INFO  Test duration: 0.36 secs
2022-02-25 16:15:06,908 INFO  Test final outcome:  BLOCKED
2022-02-25 16:15:06,909 INFO  Test outcome reason: sudo<outp> returned exit code 2 (expected ==1)
2022-02-25 16:15:06,909 INFO  
